"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set the DJANGO_SECRET_KEY environment variable in production; the
# hardcoded value below is only a fallback for local development.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-8w)=@xxo+-7h99nz3@v913o0g(im3sy_%7u&2wed!_4@&qkf4o',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
] + ['.vercel.app']

CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']

# Vercel's edge terminates HTTPS and forwards to the app over plain HTTP,
# setting this header - without telling Django to trust it, every request
# looks insecure and CSRF/cookie-security checks misbehave.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'dashboard',
    'inventory',
    'expenses',
    'reports',
    'products',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# If DATABASE_URL is set (a real, persistent Postgres database - e.g. a
# free Neon or Supabase project), use it. This is what makes data survive
# on Vercel: without it, every cold start gets a throwaway copy of the
# bundled SQLite file (see the fallback below) and anything written
# in one serverless instance can vanish the moment another one takes
# over the next request.
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }

else:
    # No persistent database configured - fall back to SQLite. On Vercel
    # the deployed project files are read-only (only /tmp is writable),
    # so the bundled db.sqlite3 can't be written to as-is; copying it into
    # /tmp on cold start makes the app usable but NOT persistent - every
    # cold start (and every separate serverless instance) gets its own
    # fresh copy, so data written here can disappear at any time. Set
    # DATABASE_URL (above) to fix this properly.
    if os.environ.get('VERCEL'):
        import shutil

        _writable_db = Path('/tmp/db.sqlite3')

        if not _writable_db.exists():
            shutil.copy(BASE_DIR / 'db.sqlite3', _writable_db)

        _db_path = _writable_db
    else:
        _db_path = BASE_DIR / 'db.sqlite3'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _db_path,
            # SQLite only allows one writer at a time. Without a busy
            # timeout, a request that arrives while another write is
            # still in flight (e.g. two tabs, or a request overlapping a
            # session write) gets an immediate "database is locked"
            # error instead of just waiting a moment for its turn.
            'OPTIONS': {
                'timeout': 20,
            },
        }
    }

    # WAL mode lets SQLite handle concurrent reads/writes far more
    # gracefully than its default rollback-journal mode (fewer/shorter
    # locks), which matters since Django's dev server handles requests
    # on multiple threads by default.
    from django.db.backends.signals import connection_created  # noqa: E402

    def _enable_sqlite_wal(sender, connection, **kwargs):
        if connection.vendor == 'sqlite':
            with connection.cursor() as cursor:
                cursor.execute('PRAGMA journal_mode=WAL;')
                cursor.execute('PRAGMA busy_timeout=20000;')

    connection_created.connect(_enable_sqlite_wal)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (product images, uploaded documents, etc.)

MEDIA_URL = 'media/'

# On Vercel the project directory is read-only outside /tmp, so writing
# an uploaded file straight to BASE_DIR/media would fail outright. Use
# /tmp there instead so uploads at least succeed - NOTE this has the same
# non-persistence caveat as the SQLite /tmp fallback above: it's wiped on
# every cold start / separate serverless instance. For uploads that must
# survive, use real object storage (e.g. Cloudinary, S3, R2) instead.
if os.environ.get('VERCEL'):
    MEDIA_ROOT = Path('/tmp/media')
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
# https://docs.djangoproject.com/en/6.0/topics/auth/default/

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'