# Generated by Django 6.0.7 on 2026-08-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Stock currently on hand. Decreases automatically as sales are made in the POS.'),
        ),
    ]
